### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by luiisgallego** [luiisgallego/TFM_FunestERP#1]
Estos serán utilizados para construir una imagen narrativa inicial del proyecto al que nos enfrentamos.

- [Casos de uso vs Historias de usuario](https://medium.com/bigperu/casos-de-uso-y-historias-de-usuario-283bb974b6a1)

- Son realmente necesarios? Investigar.

**Comment by luiisgallego** [comment]
Se realizarán más adelante en el caso de que sean necesario.

**Comment by luiisgallego** [comment]
No se van a hacer.

**Comment by JJ** [comment]
@luiisgallego ¿Por?
